name: CI

on:
  push:
    branches: [ main ]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Say hi
        run: echo "CI pipeline placeholder – next: lint, test, build, deploy"
